# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b591069c40d8d3b949b0192dce0c52913cf65a46a47453be14888eb5da5be414acee270b1642b6db5b889ece0a14f5361d35d484d9d8e098a099ce1e429314f

test:
  secret_key_base: 4a83e63f03d6bcdf117f89c16154fad3cf847da28967ba5b654a90c4f4c5737749f807f5ac72bad71637dab88585aa9d3252436ee006fca512fea65e6e017164

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
